#!/usr/bin/env python3
"""
gen-brave-theme.py — technicolor palette -> Brave/Chromium theme (unpacked
extension at ~/.config/brave-technicolor-theme).

The frame/tab-strip is painted in the chroma KEY so the band-limited
technicolor-chromakey-brave.glsl shader (hyprland.conf) renders it as glass
to the wallpaper; the toolbar/tabs/new-tab page take the palette colors.

Install — add two lines to ~/.config/brave-flags.conf (NO manual
brave://extensions step needed; verified working on Chrome 149):
    --load-extension=~/.config/brave-technicolor-theme   # auto-loads the theme each launch
    --remote-debugging-port=9222                          # lets the pipeline hot-recolor (see brave-theme-reload.py)
Chromium flashes a dismissable "turn off developer-mode extensions" bubble on
launch — cosmetic. (Manual alternative: brave://extensions -> Developer mode
-> Load unpacked -> this folder.)

Live recolor: Chromium bakes the theme into a profile-side cache, so just
rewriting these files does nothing on its own. brave-theme-reload.py forces a
re-read + re-apply via the browser-level CDP command Extensions.loadUnpacked
(over the DevTools port) — no tab, no window. The version below is bumped from
the palette so each load is a distinct version.
"""
import json
import os
import sys

sys.path.insert(0, os.path.expanduser("~/.config/hypr"))
gd = __import__("gen-discord-theme")

OUT = os.path.expanduser("~/.config/brave-technicolor-theme")


def main():
    p = gd.load()
    # Brave intentionally SWAPS primary/secondary vs the other apps — the user
    # wants the browser's palette flipped (toolbar takes the secondary colour,
    # tabs take the primary). Just swap which gradient end feeds which here.
    primary = gd.rgb(p.get("GRADIENT_START", "#3e71c0"))
    secondary = gd.rgb(p.get("GRADIENT_END", "#cd9b39"))
    accent = gd.rgb(p.get("VISIBLE", "#758994"))
    ink_p = gd.ink_rgb(primary)
    ink_s = gd.ink_rgb(secondary)

    os.makedirs(OUT, exist_ok=True)

    # diagonal gradient NTP background, like the bar
    try:
        from PIL import Image
        W, H = 1920, 1080
        img = Image.new("RGB", (W, H))
        px = img.load()
        for y in range(H):
            for x in range(0, W, 2):
                t = (x / W + y / H) / 2.0
                col = tuple(int(primary[i] * (1 - t) + secondary[i] * t) for i in range(3))
                px[x, y] = col
                if x + 1 < W:
                    px[x + 1, y] = col
        img.save(os.path.join(OUT, "ntp_bg.png"))
        images = {"theme_ntp_background": "ntp_bg.png"}
    except Exception:
        images = {}

    # frame/tab-strip = chroma key -> the BAND-LIMITED tckeybrave shader
    # (hyprland.conf) renders it as glass. The band gate means web content
    # below the tab strip is never keyed, which is what made whole-window
    # browser keying unusable before (Twitch punch-through). Tabs themselves
    # are solid secondary pills on the glass strip.
    KEY = [1, 186, 188]
    # Bump the version from the palette so each regenerated theme is a distinct
    # version — insurance that Chromium treats Extensions.loadUnpacked as a real
    # change and re-applies (brave-theme-reload.py does the load).
    seed = "".join("{:02x}{:02x}{:02x}".format(*c) for c in (primary, secondary, accent))
    rev = sum(ord(ch) for ch in seed) % 65000
    manifest = {
        "manifest_version": 3,
        "name": "Technicolor",
        "version": "1.0." + str(rev),
        "description": "Wallpaper-palette theme (generated by gen-brave-theme.py)",
        "theme": {
            "images": images,
            "colors": {
                "frame": KEY,
                "frame_inactive": KEY,
                "background_tab": list(secondary),
                "background_tab_inactive": list(secondary),
                "toolbar": list(primary),
                "tab_text": list(ink_p),
                "tab_background_text": list(ink_s),
                "bookmark_text": list(ink_p),
                "toolbar_button_icon": list(ink_p),
                "omnibox_background": [int(c * 0.94) for c in primary],
                "omnibox_text": list(ink_p),
                "ntp_background": list(primary),
                "ntp_text": list(ink_p),
                "ntp_link": list(accent),
                "button_background": list(accent),
            },
            "properties": {
                "ntp_background_alignment": "center",
                "ntp_background_repeat": "no-repeat",
            },
        },
    }
    with open(os.path.join(OUT, "manifest.json"), "w") as f:
        json.dump(manifest, f, indent=2)


if __name__ == "__main__":
    main()
