#!/usr/bin/env python3
"""
gen-spotify-theme.py — "Technicolor Glass" for Spotify (Spicetify).

Same architecture as the Discord setup:
  * STATIC structure (user.css): the glass layout in terms of var(--tc-*), with
    @property registrations + a transition on html:root so palette changes
    CROSS-FADE — identical var names and fade as Discord.
  * LIVE colors: the technicolor-sync.js extension polls 127.0.0.1:9573 (served
    from $XDG_RUNTIME_DIR/technicolor-colors.json, written by gen-discord-theme
    on every wallpaper change) and sets --tc-* on <html>. No re-apply needed.
  * color.ini: static fallback scheme baked at `spicetify apply` time.

Look (mirrors Technicolor Glass on Discord):
  raw gradient (primary->secondary, 135deg) behind everything / in the gaps
  main view        = solid PRIMARY  + contrast text
  left/right/player= solid SECONDARY + contrast text
  global nav (top) = frosted blur over the gradient
Borrows spicetify's --spice-* remap (its css-map rewrites Spotify's own CSS to
use those vars) so coverage is broad without chasing class names.

Apply once:  spicetify config current_theme Technicolor extensions technicolor-sync.js
             spicetify apply
"""
import os
import sys

# reuse the exact palette/contrast engine from the Discord generator
sys.path.insert(0, os.path.expanduser("~/.config/hypr"))
gd = __import__("gen-discord-theme")

THEME_DIR = os.path.expanduser("~/.config/spicetify/Themes/Technicolor")
FADE = gd.FADE


def pick_key(palette_rgbs):
    """Per-wallpaper chroma key: the candidate color farthest from everything
    that will actually be rendered (palette colors, inks, black/white/greys —
    album art and text live near those). The shader self-calibrates by sampling
    the window's top-left pixel, so ONLY the CSS needs the key value."""
    avoid = list(palette_rgbs) + [
        (0, 0, 0), (255, 255, 255),
        (64, 64, 64), (128, 128, 128), (192, 192, 192),
        (21, 21, 26), (245, 245, 248),
    ]
    candidates = []
    for r in (0, 64, 128, 192, 255):
        for g in (0, 64, 128, 192, 255):
            for b in (0, 64, 128, 192, 255):
                # skip near-corner colors (pure primaries/secondaries): flat-design
                # album art uses exactly those; an exact-match key there = holes
                if sum(1 for v in (r, g, b) if v in (0, 255)) >= 2:
                    continue
                candidates.append((r, g, b))

    def mind(c):
        return min(sum((c[i] - a[i]) ** 2 for i in range(3)) for a in avoid)

    return max(candidates, key=mind)


def main():
    p = gd.load()
    # bar gradient pair (see gen-discord-theme.py): primary = END, secondary = START
    primary = gd.rgb(p.get("GRADIENT_END", "#cd9b39"))
    secondary = gd.rgb(p.get("GRADIENT_START", "#3e71c0"))
    third = gd.rgb(p.get("OCCUPIED", "#546c8a"))
    accent = gd.rgb(p.get("VISIBLE", "#758994"))
    V = gd.compute_vars(primary, secondary, third, accent)
    key = pick_key([primary, secondary, third, accent,
                    tuple(int(c * 0.85) for c in secondary),
                    tuple(int(c * 0.9) for c in secondary)])
    KEY = "#{:02x}{:02x}{:02x}".format(*key)

    # ---------- color.ini: static fallback, baked at apply time ----------
    ink_s = gd.hexs(gd.ink_rgb(secondary)).lstrip("#")
    scheme = {
        "text": ink_s,
        "subtext": ink_s,
        "main": V["p"].lstrip("#"),
        "main-elevated": V["p"].lstrip("#"),
        "highlight": V["s"].lstrip("#"),
        "highlight-elevated": V["s"].lstrip("#"),
        "sidebar": V["s"].lstrip("#"),
        "player": V["s"].lstrip("#"),
        "card": V["s"].lstrip("#"),
        "shadow": "000000",
        "selected-row": V["tp"].lstrip("#"),
        "button": V["a"].lstrip("#"),
        "button-active": V["a"].lstrip("#"),
        "button-disabled": "777777",
        "tab-bar": V["s"].lstrip("#"),
        "notification": V["s"].lstrip("#"),
        "notification-error": "e0405a",
        "misc": "888888",
    }
    os.makedirs(THEME_DIR, exist_ok=True)
    with open(os.path.join(THEME_DIR, "color.ini"), "w") as f:
        f.write("[base]\n")
        for k, v in scheme.items():
            f.write("{:<20}= {}\n".format(k, v))

    # ---------- user.css: the static glass structure ----------
    props = "\n".join(
        "@property --tc-{} {{ syntax: '<color>'; inherits: true; initial-value: {}; }}".format(k, v)
        for k, v in V.items() if k not in gd.FILTER_KEYS)
    fade = ("html:root { transition: "
            + ", ".join("--tc-{} {}".format(k, FADE) for k in V if k not in gd.FILTER_KEYS)
            + "; }")
    fallbacks = ":root {\n" + "\n".join(
        "  --tc-{}: {};".format(k, v) for k, v in V.items()) + "\n}"

    css = f"""/* Technicolor Glass for Spotify — STATIC structure, auto-generated by
 * gen-spotify-theme.py. Live colors arrive via the technicolor-sync extension
 * (--tc-* vars on <html>); these baked values are only the fallback. */

{props}

{fade}

{fallbacks}

/* ===== remap spicetify's --spice-* vars onto the live palette =====
 * (spicetify's css-map rewrote Spotify's own CSS to use these, so most
 * surfaces follow the live colors + cross-fade automatically) */
:root {{
  --spice-main: var(--tc-p);
  --spice-main-elevated: var(--tc-p);
  --spice-sidebar: var(--tc-s);
  --spice-player: var(--tc-s);
  --spice-card: var(--tc-s);
  --spice-tab-bar: var(--tc-s);
  --spice-highlight: rgba(0,0,0,0.10);
  --spice-highlight-elevated: rgba(0,0,0,0.14);
  --spice-shadow: rgba(0,0,0,0.25);
  --spice-selected-row: var(--tc-tp);
  --spice-button: var(--tc-a);
  --spice-button-active: var(--tc-a);
  --spice-notification: var(--tc-s);
  /* default text = contrast vs SECONDARY (sidebar/player chrome) */
  --spice-text: var(--tc-ts1);
  --spice-subtext: var(--tc-ts3);
  --spice-misc: var(--tc-ts3);
}}

/* ===== background = DYNAMIC CHROMA KEY {KEY} — picked per wallpaper as the
 * color farthest from the entire palette/inks/greys, so content never sits
 * near the key (near-key palettes = noisy edges). The shader self-calibrates
 * by sampling the window's top-left pixel; nothing else needs to know the
 * key. Keyed to transparent at the compositor -> real see-through. ===== */
body, #main, .Root__top-container {{
  background: {KEY} !important;
  background-image: none !important;
}}

/* ===== main view = solid PRIMARY, text contrasts primary ===== */
.Root__main-view {{
  background: var(--tc-p) !important;
  --spice-text: var(--tc-tc1);
  --spice-subtext: var(--tc-tc3);
  --background-base: var(--tc-p);
  --text-base: var(--tc-tc1);
  --text-subdued: var(--tc-tc3);
}}

/* ===== left library / right now-playing / bottom player = solid SECONDARY ===== */
.Root__nav-bar, .Root__right-sidebar {{
  background: var(--tc-s) !important;
  border-radius: 12px;
  overflow: hidden;
  --spice-text: var(--tc-ts1);
  --spice-subtext: var(--tc-ts3);
  --background-base: var(--tc-s);
  --text-base: var(--tc-ts1);
  --text-subdued: var(--tc-ts3);
}}
/* ===== bottom player = inset SECONDARY block aligned with the columns ===== */
.Root__now-playing-bar {{
  background: transparent !important;
  --spice-text: var(--tc-ts1);
  --spice-subtext: var(--tc-ts3);
  --text-base: var(--tc-ts1);
  --text-subdued: var(--tc-ts3);
}}
footer[data-testid="now-playing-bar"], .main-nowPlayingBar-nowPlayingBar {{
  background: var(--tc-s) !important;
  border-radius: 12px;
  /* grid row already insets the sides — extra side margins broke column alignment */
  margin: 0 0 8px 0;
}}

/* ===== top nav: TRANSPARENT (liquid glass shows through); clusters become
 * their own pills (left: menu dots + history, right: bell/people/profile) ===== */
.Root__globalNav, .Root__top-bar {{
  background: transparent !important;
  box-shadow: none !important;
  --spice-text: var(--tc-st1);
  --spice-subtext: var(--tc-st3);
  --text-base: var(--tc-st1);
  --text-subdued: var(--tc-st3);
}}
.main-globalNav-historyButtonsContainer {{ margin-left: 8px; padding-left: 0; }}
.main-globalNav-historyButtonsWrapper {{
  background: var(--tc-s);
  border-radius: 9999px;
  padding: 2px 10px;
  width: fit-content;           /* don't stretch past the sidebar column */
  --spice-text: var(--tc-ts1);
  --spice-subtext: var(--tc-ts3);
}}
.main-globalNav-contentRight {{ margin-right: 8px; }}
.main-topBar-topbarContentRight {{
  background: var(--tc-s);
  border-radius: 9999px;
  padding: 3px 8px;
  --spice-text: var(--tc-ts1);
  --spice-subtext: var(--tc-ts3);
}}
/* search pill in the nav = PRIMARY box with contrast text (like Discord's) */
.Root__globalNav input, .main-globalNav-searchInput {{
  background-color: var(--tc-p) !important;
  color: var(--tc-tc1) !important;
}}
.Root__globalNav input::placeholder {{ color: var(--tc-tc4) !important; }}
[data-testid="search-input"], .main-globalNav-searchSection form {{
  background-color: var(--tc-p) !important;
  border-radius: 9999px;
}}

/* THE carousel edge fade: every shelf's contentArea carries 120px-wide dark
   gradient ::before/::after overlays (left+right). Remove them entirely. */
html [class*="searchCategory-contentArea"]::before,
html [class*="searchCategory-contentArea"]::after {{
  content: none !important;
  background: none !important;
  background-image: none !important;
}}

/* activated control toggles (loop on, liked checkmark, shuffle on) use the
   "bright accent" tokens — make them the per-surface INK (black/white) for
   readability instead of a palette color */
:root, .Root__nav-bar, .Root__right-sidebar, .Root__now-playing-bar {{
  --spice-button-active: var(--tc-ts0);
  --text-bright-accent: var(--tc-ts0);
  --essential-bright-accent: var(--tc-ts0);
}}
.Root__main-view {{
  --spice-button-active: var(--tc-tc0);
  --text-bright-accent: var(--tc-tc0);
  --essential-bright-accent: var(--tc-tc0);
}}

/* kill Spotify's own dark decorative gradients (entity/home/page headers) —
   they painted ugly dark fades over the technicolor surfaces */
[class*="entityHeader-background"], [class*="entityHeader-overlay"],
[class*="actionBarBackground"],
[class*="homeHeader"], [class*="homeHeader"]::before, [class*="homeHeader"]::after {{
  background: none !important;
  background-image: none !important;
}}

/* The entity-header text (artist/album title + "Verified by Spotify" + monthly
   listeners) sits over Spotify's PHOTO banner, not a theme surface — so the
   blanket encore-base -> tc-tc1 mapping below makes it dark and unreadable on
   the photo. Force the whole header text block white + a soft shadow so it
   reads over any image (Spotify's own white, minus the dark scrim we removed).
   Scoped to main-entityHeader-headerText so body text elsewhere is unaffected.
   html body = higher specificity than the encore-base rule, so it wins. */
html body [class*="main-entityHeader-headerText"] *,
html body [class*="main-entityHeader-subtitle"] {{
  color: #fff !important;
  text-shadow: 0 1px 6px rgba(0,0,0,0.55) !important;
}}
/* byline icons (the Spotify logo on "Made for X" / algorithmic playlists) use
   SVG fill, not color, and keep an explicit dark fill — so they show as a black
   smudge over the photo. Follow the white text via currentColor. */
html body [class*="main-entityHeader-headerText"] svg {{
  fill: currentColor !important;
  filter: drop-shadow(0 1px 4px rgba(0,0,0,0.5));
}}

/* ALL masks in the main view die (carousel edge fades, marquee text fades) —
   technicolor doesn't fade, content just ends. Spinner keeps its conic mask.
   (html prefix = exact selectors verified live; class-based masks are hashed) */
html .Root__main-view *:not([class*="loadingSpinner"]) {{
  mask-image: none !important; -webkit-mask-image: none !important;
}}

/* right (now playing) bar = ONE COLOR: the shell's secondary, nothing else.
   Kills bg-images, bg-colors, and ::before/::after dark gradient washes — the
   REAL painters were pseudo-elements (found via computed-style eval channel).
   Buttons keep their own backgrounds. */
html .Root__right-sidebar * {{ background-image: none !important; }}
html .Root__right-sidebar *:not(button):not([role="button"]) {{ background-color: transparent !important; }}
html .Root__right-sidebar *::before, html .Root__right-sidebar *::after {{
  background: none !important; background-image: none !important;
}}
/* the About-artist card is one giant <button> (exempt from the button-spare
   above) — flatten it too, ONE color means one color */
html .Root__right-sidebar [class*="aboutArtist"],
html .Root__right-sidebar [class*="aboutArtist"] * {{
  background: transparent !important;
  background-image: none !important;
}}

/* encore text classes ignore the scoped vars — map them to the per-surface
   inks (spice-text/subtext are scoped per panel, so this is surface-aware) */
html [class*="encore-internal-color-text-base"] {{ color: var(--spice-text) !important; }}
html [class*="encore-internal-color-text-subdued"] {{ color: var(--spice-subtext) !important; }}

/* NO SHADOWS ANYWHERE: Spotify's elevation box-shadows composite over the
   chroma-key background as "darkened key" pixels — too far from the key to be
   keyed out -> opaque BLACK HALOS around every rounded element. Technicolor is
   flat; shadows die. */
html *, html *::before, html *::after {{
  box-shadow: none !important;
  text-shadow: none !important;
}}
html [class*="shadow"] {{ box-shadow: none !important; filter: none !important; }}

/* nav pill icons (3 dots, history arrows, bell/people): force the panel ink —
   their encore-tertiary buttons use an unmapped (white) token */
html .main-globalNav-historyButtonsWrapper button,
html .main-globalNav-historyButtonsWrapper button *,
html .main-topBar-topbarContentRight button:not([class*="Avatar"]),
html .main-topBar-topbarContentRight button svg {{
  color: var(--tc-ts1) !important;
}}

/* right-panel links: some (NPV title artists) are hardcoded white @70% — force
   the panel ink across the board */
html .Root__right-sidebar a {{ color: var(--tc-ts1) !important; }}

/* links follow the high-contrast tinted primary, like Discord */
a {{ color: var(--tc-tp); }}
"""
    with open(os.path.join(THEME_DIR, "user.css"), "w") as f:
        f.write(css)


if __name__ == "__main__":
    main()
