#!/usr/bin/env python3
"""
gen-gtk-theme.py — technicolor palette -> GTK3 theme, hot-applied.

This is the LIVE color channel for Brave/Chromium: with brave://settings/
appearance set to "Use GTK", Chromium derives its frame/toolbar/omnibox/menu
colors from the GTK theme and follows GTK theme CHANGES instantly (the same
mechanism that makes light/dark switches apply live). Extension themes can't
do this — Chromium bakes them into a profile-side cache that only the manual
reload button on brave://extensions rebuilds (verified: regenerating the
unpacked theme then disable/enable-bouncing or even restarting Brave still
rendered the stale cached colors).

GTK caches a theme by NAME, so two identical copies are written
(Technicolor-A / Technicolor-B) and each run flips gtk-theme-name to the one
not currently active — every GTK app (Brave included) re-reads and recolors.

Color mapping (matches what Chromium samples from GTK3):
  window bg  (theme_bg_color) -> toolbar          = palette primary
  headerbar                   -> frame/tab strip  = palette secondary
  entry                       -> omnibox          = darkened primary
  selected                    -> selection/accent = palette accent

Revert to your old GTK theme any time:
  gsettings set org.gnome.desktop.interface gtk-theme 'Breeze'
"""
import os
import subprocess
import sys

sys.path.insert(0, os.path.expanduser("~/.config/hypr"))
gd = __import__("gen-discord-theme")

THEMES = os.path.expanduser("~/.local/share/themes")


def hx(c):
    return "#{:02x}{:02x}{:02x}".format(*c)


def mix(a, b, t):
    return tuple(int(a[i] * (1 - t) + b[i] * t) for i in range(3))


def main():
    p = gd.load()
    primary = gd.rgb(p.get("GRADIENT_END", "#cd9b39"))
    secondary = gd.rgb(p.get("GRADIENT_START", "#3e71c0"))
    accent = gd.rgb(p.get("VISIBLE", "#758994"))
    ink_p = gd.ink_rgb(primary)
    ink_s = gd.ink_rgb(secondary)
    ink_a = gd.ink_rgb(accent)
    prim_dim = mix(primary, (0, 0, 0) if sum(ink_p) < 384 else (255, 255, 255), 0.06)
    sec_dim = mix(secondary, (0, 0, 0), 0.12)

    css = """/* generated by gen-gtk-theme.py — do not edit */
@define-color theme_bg_color {prim};
@define-color theme_fg_color {inkp};
@define-color theme_base_color {prim_dim};
@define-color theme_text_color {inkp};
@define-color theme_selected_bg_color {acc};
@define-color theme_selected_fg_color {inka};
@define-color insensitive_bg_color {prim};
@define-color insensitive_fg_color alpha({inkp}, 0.5);
@define-color borders alpha({inkp}, 0.18);
@define-color unfocused_borders alpha({inkp}, 0.12);

window, dialog {{ background-color: {prim}; color: {inkp}; }}
headerbar, .titlebar {{ background: {sec}; background-image: none; color: {inks}; border-color: transparent; }}
headerbar:backdrop, .titlebar:backdrop {{ background: {sec_dim}; color: alpha({inks}, 0.75); }}
headerbar label, .titlebar label {{ color: {inks}; }}
entry {{ background-color: {prim_dim}; color: {inkp}; border-color: alpha({inkp}, 0.22); }}
entry selection {{ background-color: {acc}; color: {inka}; }}
menu, .menu, popover, popover.background {{ background-color: {sec}; color: {inks}; }}
menu menuitem:hover, .menu menuitem:hover, popover modelbutton:hover {{ background-color: {acc}; color: {inka}; }}
tooltip, tooltip.background {{ background-color: {sec}; color: {inks}; }}
*:selected {{ background-color: {acc}; color: {inka}; }}
""".format(prim=hx(primary), prim_dim=hx(prim_dim), sec=hx(secondary), sec_dim=hx(sec_dim),
           acc=hx(accent), inkp=hx(ink_p), inks=hx(ink_s), inka=hx(ink_a))

    for name in ("Technicolor-A", "Technicolor-B"):
        d = os.path.join(THEMES, name, "gtk-3.0")
        os.makedirs(d, exist_ok=True)
        with open(os.path.join(d, "gtk.css"), "w") as f:
            f.write(css)
        with open(os.path.join(THEMES, name, "index.theme"), "w") as f:
            f.write("[Desktop Entry]\nType=X-GNOME-Metatheme\nName={n}\n"
                    "Comment=Technicolor generated theme\nEncoding=UTF-8\n\n"
                    "[X-GNOME-Metatheme]\nGtkTheme={n}\nMetacityTheme={n}\n".format(n=name))

    # flip to whichever copy isn't active so GTK (and Chromium) re-read
    try:
        cur = subprocess.run(["gsettings", "get", "org.gnome.desktop.interface", "gtk-theme"],
                             capture_output=True, text=True).stdout.strip().strip("'")
        nxt = "Technicolor-B" if cur == "Technicolor-A" else "Technicolor-A"
        subprocess.run(["gsettings", "set", "org.gnome.desktop.interface", "gtk-theme", nxt],
                       capture_output=True)
    except Exception:
        pass


if __name__ == "__main__":
    main()
