#!/usr/bin/env python3
"""gen-wlogout-style.py — wallpaper-themed liquid-glass wlogout style.css.

A single horizontal row of 6 OPAQUE palette-colored buttons on a rounded,
palette-tinted GLASS strip (the GTK `grid` is the box; wlogout's `logout_dialog`
layer is whitelisted in hyprland.lua so hyprwater refracts the strip — no
chromakey). Sizing/position is handled by lo-wlogout.sh's CLI flags; this file
is purely colors + shape. Regenerated on every wallpaper change.
"""
import os
import sys

sys.path.insert(0, os.path.expanduser("~/.config/hypr"))
gd = __import__("gen-discord-theme")

OUT = os.path.expanduser("~/.config/wlogout/style.css")
SVGS = "/usr/share/wlogout/assets"                       # source SVGs (black paths)
CACHE = os.path.expanduser("~/.cache/wlogout-icons")     # recolored png cache


def _recolor_icons(ink):
    """Render each wlogout SVG in the auto-contrast `ink` color → cached PNGs.
    The stock PNGs are a fixed lavender that CSS can't recolor (raster), so we
    pre-render the SVG paths in the button's contrast ink, like every other
    surface's auto-contrast text/icons. Returns the cache dir (or None on fail)."""
    import subprocess
    os.makedirs(CACHE, exist_ok=True)
    hexink = "#{:02X}{:02X}{:02X}".format(*ink)
    btns = "lock logout suspend hibernate shutdown reboot".split()
    ok = True
    for b in btns:
        src = f"{SVGS}/{b}.svg"
        dst = f"{CACHE}/{b}.png"
        if not os.path.exists(src):
            ok = False; continue
        try:
            # render SVG → recolor non-transparent pixels to ink (keeps alpha shape)
            subprocess.run(
                ["magick", "-background", "none", src, "-resize", "256x256",
                 "-fill", hexink, "-colorize", "100", dst],
                capture_output=True, timeout=10, check=True)
        except Exception:
            ok = False
    return CACHE if ok else None


def main():
    p = gd._tune_palette(gd._raw_env(), "wlogout")
    btn   = gd.rgb(p.get("GRADIENT_START", "#3e71c0"))   # opaque button base
    hover = gd.rgb(p.get("GRADIENT_END", "#cd9b39"))     # opaque hover
    # (glass strip is a fixed near-clear neutral — no palette tint, like the
    #  bar/wofi/pie glass; only the buttons take palette colors)
    btn_ink   = gd.ink_rgb(btn)
    hover_ink = gd.ink_rgb(hover)

    def rgba(c, a): return f"rgba({c[0]}, {c[1]}, {c[2]}, {a})"
    def rgb(c):     return f"rgb({c[0]}, {c[1]}, {c[2]})"

    btns = "lock logout suspend hibernate shutdown reboot".split()
    # auto-contrast icons: render SVGs in the button's contrast ink (matches text)
    icondir = _recolor_icons(btn_ink) or "/usr/share/wlogout/icons"
    ext = "png"
    icon_css = "\n".join(
        f'#{b} {{ background-image: image(url("{icondir}/{b}.{ext}")); }}' for b in btns
    )

    css = f"""/* generated by gen-wlogout-style.py — do not edit (regenerated on wallpaper change) */
* {{
    background-image: none;
    box-shadow: none;
    font-family: "JetBrainsMono Nerd Font", sans-serif;
}}

/* fully transparent fullscreen layer — only the grid strip is drawn */
window {{ background-color: transparent; }}

/* the glass strip (the box around the buttons). NEAR-CLEAR neutral at low alpha
   — like the bar/wofi/pie, the hyprwater layer does the glass; a palette tint
   here would cast a color the other glass surfaces don't have. Low alpha = clear
   refraction, no color. */
grid {{
    /* near-clear, matching the wofi glass surface (rgba ~0.06) — hyprwater does
       the glass; anything heavier reads as a tint the other glass doesn't have. */
    background-color: rgba(150, 150, 160, 0.06);
    border-radius: 26px;
    padding: 22px;
}}

/* OPAQUE palette buttons (like everything else), rounded, with spacing handled
   by wlogout's --row/--column-spacing flags */
button {{
    color: {rgb(btn_ink)};
    background-color: {rgb(btn)};
    border: none;
    border-radius: 14px;
    min-width: 92px;
    min-height: 92px;
    background-repeat: no-repeat;
    /* OPTICAL centering: the text label sits in the lower band of the button, so
       a true-center icon reads as too low. Lift the icon to ~38% vertical so the
       icon + label group is visually balanced. (top padding pushes the label down
       a touch for breathing room under the icon.) */
    background-position: center 38%;
    background-size: 38%;
    padding-bottom: 6px;
    transition: background-color 0.16s ease;
}}

button:hover, button:focus, button:active {{
    color: {rgb(hover_ink)};
    background-color: {rgb(hover)};
    outline-style: none;
}}

{icon_css}
"""
    try:
        with open(OUT, "w") as f:
            f.write(css)
    except Exception as e:
        sys.stderr.write(f"[gen-wlogout-style] {e}\n")


if __name__ == "__main__":
    main()
