#!/usr/bin/env python3
"""
gen-brave-theme.py — technicolor palette -> Brave/Chromium theme (unpacked
extension at ~/.config/brave-technicolor-theme).

Browser chrome is native Chromium: themes can color the frame/toolbar/tabs and
the new-tab page (incl. a generated gradient background) but CANNOT be updated
live — Brave applies a theme when the extension (re)loads. So this regenerates
the files on every wallpaper change, and Brave picks it up when you hit the
reload icon on the extension (brave://extensions) or restart Brave.

One-time install: brave://extensions -> Developer mode ON -> Load unpacked ->
~/.config/brave-technicolor-theme
"""
import json
import os
import sys

sys.path.insert(0, os.path.expanduser("~/.config/hypr"))
gd = __import__("gen-discord-theme")

OUT = os.path.expanduser("~/.config/brave-technicolor-theme")


def main():
    p = gd.load()
    primary = gd.rgb(p.get("GRADIENT_END", "#cd9b39"))
    secondary = gd.rgb(p.get("GRADIENT_START", "#3e71c0"))
    accent = gd.rgb(p.get("VISIBLE", "#758994"))
    ink_p = gd.ink_rgb(primary)
    ink_s = gd.ink_rgb(secondary)

    os.makedirs(OUT, exist_ok=True)

    # diagonal gradient NTP background, like the bar
    try:
        from PIL import Image
        W, H = 1920, 1080
        img = Image.new("RGB", (W, H))
        px = img.load()
        for y in range(H):
            for x in range(0, W, 2):
                t = (x / W + y / H) / 2.0
                col = tuple(int(primary[i] * (1 - t) + secondary[i] * t) for i in range(3))
                px[x, y] = col
                if x + 1 < W:
                    px[x + 1, y] = col
        img.save(os.path.join(OUT, "ntp_bg.png"))
        images = {"theme_ntp_background": "ntp_bg.png"}
    except Exception:
        images = {}

    manifest = {
        "manifest_version": 3,
        "name": "Technicolor",
        "version": "1.0",
        "description": "Wallpaper-palette theme (generated by gen-brave-theme.py)",
        "theme": {
            "images": images,
            "colors": {
                # solid frame — keying browsers is OFF (it punched holes in web
                # content that matched the key, e.g. Twitch streams)
                "frame": list(secondary),
                "frame_inactive": list(secondary),
                "toolbar": list(primary),
                "tab_text": list(ink_p),
                "tab_background_text": list(ink_s),
                "bookmark_text": list(ink_p),
                "toolbar_button_icon": list(ink_p),
                "omnibox_background": [int(c * 0.94) for c in primary],
                "omnibox_text": list(ink_p),
                "ntp_background": list(primary),
                "ntp_text": list(ink_p),
                "ntp_link": list(accent),
                "button_background": list(accent),
            },
            "properties": {
                "ntp_background_alignment": "center",
                "ntp_background_repeat": "no-repeat",
            },
        },
    }
    with open(os.path.join(OUT, "manifest.json"), "w") as f:
        json.dump(manifest, f, indent=2)


if __name__ == "__main__":
    main()
