#!/usr/bin/env python3
"""
window-geometry.py — remember & restore each app's window state across reboots:
whether it was tiled or floating, and (when floating) its monitor + position +
size. Hyprland 0.55 has no native equivalent.

  - Polls `hyprctl clients`; per window class records tiled-vs-floating, plus
    floating geometry (monitor-relative position + size). Saved to JSON
    (survives reboots).
  - Writes matching window rules into a sourced conf file AND applies them live:
      floating -> `float on` + `monitor`/`size`/`move`  (spawns at the saved spot)
      tiled    -> `tile on`                              (opens tiled)
    The rules exist BEFORE a window opens, so it spawns in the right state with
    no jump. The conf is sourced by hyprland.conf so it also works from the
    first launch after a reboot.

Per-app (by class). First time an app is seen it uses its default; once you
tile/float/move/size it, that's remembered.
"""
import json
import os
import re
import subprocess
import time

STATE = os.path.expanduser("~/.local/state/hypr/window-geometry.json")
CONF = os.path.expanduser("~/.config/hypr/window-geometry.conf")
POLL = 2.5
MIN_SIZE = 50  # ignore tiny/transient surfaces
EXCLUDE = {"com.dec05eba.gpu_screen_recorder", "gsr-ui", "hyprland-run", "wofi"}

_max_mons = 0  # most monitors ever seen; used to pause recording when one is off


def load():
    try:
        with open(STATE) as f:
            raw = json.load(f)
    except Exception:
        return {}
    out = {}
    for cls, v in raw.items():
        if isinstance(v, list) and len(v) == 5:  # legacy floating-only format
            out[cls] = {"floating": True, "mon": v[0], "x": v[1],
                        "y": v[2], "w": v[3], "h": v[4]}
        elif isinstance(v, dict):
            out[cls] = v
    return out


geo = load()  # class -> {"floating": bool, "mon","x","y","w","h" (when known)}


def hyprctl_json(what):
    try:
        r = subprocess.run(["hyprctl", "-j", what],
                           capture_output=True, text=True, timeout=2)
        return json.loads(r.stdout)
    except Exception:
        return None


def rules_for(cls, v):
    """Window-rule bodies (without the leading 'windowrule = ') for this app."""
    m = "match:class ^(" + re.escape(cls) + ")$"
    if not v.get("floating"):
        return ["tile on, " + m]
    out = ["float on, " + m]
    if all(v.get(k) is not None for k in ("mon", "x", "y", "w", "h")):
        out += [f"monitor {v['mon']}, {m}",
                f"size {v['w']} {v['h']}, {m}",
                f"move {v['x']} {v['y']}, {m}"]
    return out


def write_conf():
    try:
        os.makedirs(os.path.dirname(CONF), exist_ok=True)
        out = ["# Auto-generated by ~/.config/hypr/window-geometry.py — remembered",
               "# per-app window state (tiled/floating + floating geometry),",
               "# regenerated whenever a window changes. Do not edit by hand.", ""]
        for cls in sorted(geo):
            for r in rules_for(cls, geo[cls]):
                out.append("windowrule = " + r)
        tmp = CONF + ".tmp"
        with open(tmp, "w") as f:
            f.write("\n".join(out) + "\n")
        os.replace(tmp, CONF)
    except Exception:
        pass


def write_state():
    try:
        os.makedirs(os.path.dirname(STATE), exist_ok=True)
        tmp = STATE + ".tmp"
        with open(tmp, "w") as f:
            json.dump(geo, f)
        os.replace(tmp, STATE)
    except Exception:
        pass


def apply_live(cls, v):
    """Update live rules so a reopen this session uses the latest state, no
    reload needed. unset first so rules never accumulate."""
    m = "match:class ^(" + re.escape(cls) + ")$"
    for r in ["unset, " + m] + rules_for(cls, v):
        subprocess.run(["hyprctl", "keyword", "windowrule", r],
                       stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)


def poll_loop():
    global _max_mons
    while True:
        time.sleep(POLL)
        mons = hyprctl_json("monitors")
        cls_list = hyprctl_json("clients")
        if mons is None or cls_list is None:
            continue
        # Pause recording while a monitor is missing (e.g. powered off overnight):
        # windows pile onto the remaining monitor, and we must NOT overwrite the
        # real saved geometry with that squished layout. Resume once all are back.
        _max_mons = max(_max_mons, len(mons))
        if len(mons) < _max_mons:
            continue
        moff = {m["id"]: (m["name"], m["x"], m["y"]) for m in mons}
        changed = False
        for c in cls_list:
            cls = c.get("class") or ""
            if not cls or cls in EXCLUDE:
                continue
            ws = (c.get("workspace") or {}).get("name", "")
            if ws.startswith("special"):
                continue
            if c.get("floating"):
                at, sz, mid = c.get("at"), c.get("size"), c.get("monitor")
                if not at or not sz or sz[0] < MIN_SIZE or sz[1] < MIN_SIZE:
                    continue
                if mid not in moff:
                    continue
                mon, mx, my = moff[mid]
                val = {"floating": True, "mon": mon,
                       "x": at[0] - mx, "y": at[1] - my, "w": sz[0], "h": sz[1]}
            else:
                # Tiled: flip the flag but keep any prior floating geometry, so
                # un-tiling later returns the window to where it last floated.
                val = dict(geo.get(cls, {}))
                val["floating"] = False
            if geo.get(cls) != val:
                geo[cls] = val
                apply_live(cls, val)
                changed = True
        if changed:
            write_state()
            write_conf()


if __name__ == "__main__":
    poll_loop()
