#!/usr/bin/env python3
"""
window-geometry.py — remember & restore each app's window state across reboots:
whether it was tiled or floating, and (when floating) its monitor + position +
size. Hyprland 0.55 has no native equivalent.

  - Polls `hyprctl clients`; per window class records tiled-vs-floating, plus
    floating geometry (monitor-relative position + size). Saved to JSON
    (survives reboots).
  - Writes matching window rules into a sourced conf file AND applies them live:
      floating -> `float on` + `monitor`/`size`/`move`  (spawns at the saved spot)
      tiled    -> `tile on`                              (opens tiled)
    The rules exist BEFORE a window opens, so it spawns in the right state with
    no jump. The conf is sourced by hyprland.conf so it also works from the
    first launch after a reboot.

Per-app (by class). First time an app is seen it uses its default; once you
tile/float/move/size it, that's remembered.
"""
import fcntl
import json
import os
import re
import subprocess
import time

STATE = os.path.expanduser("~/.local/state/hypr/window-geometry.json")
CONF = os.path.expanduser("~/.config/hypr/window-geometry.conf")
POLL = 2.5
MIN_SIZE = 50  # ignore tiny/transient surfaces
# "Steam" (capital) is Steam's popup/dialog/toast class (the main client is the
# lowercase "steam"); recording it let a 700x330 popup poison the geometry and
# force real Steam windows tiny in the corner. Never record/reposition it.
EXCLUDE = {"com.dec05eba.gpu_screen_recorder", "gsr-ui", "hyprland-run", "wofi",
           "Steam"}

# Some XWayland apps (e.g. Godot) give their popups/tooltips the SAME class as
# the main window, so a class-only geometry rule force-sizes the popup to the
# main window's saved geometry. They differ by initial_title: the real window
# has a stable one, popups open with an empty title. For such classes, append an
# extra matcher so geometry rules hit ONLY the real window. class -> extra match.
MATCH_REFINE = {"Godot": "match:initial_title ^(Godot)$"}

_max_mons = 0  # most monitors ever seen; used to pause recording when one is off


def load():
    try:
        with open(STATE) as f:
            raw = json.load(f)
    except Exception:
        return {}
    out = {}
    for cls, v in raw.items():
        if isinstance(v, list) and len(v) == 5:  # legacy floating-only format
            out[cls] = {"floating": True, "mon": v[0], "x": v[1],
                        "y": v[2], "w": v[3], "h": v[4]}
        elif isinstance(v, dict):
            out[cls] = v
    return out


geo = load()  # class -> {"floating": bool, "mon","x","y","w","h" (when known)}


def hyprctl_json(what):
    try:
        r = subprocess.run(["hyprctl", "-j", what],
                           capture_output=True, text=True, timeout=2)
        return json.loads(r.stdout)
    except Exception:
        return None


def matcher(cls):
    """Class matcher for window rules, plus any popup-excluding refinement."""
    m = "match:class ^(" + re.escape(cls) + ")$"
    if cls in MATCH_REFINE:
        m += ", " + MATCH_REFINE[cls]
    return m


def rules_for(cls, v):
    """Window-rule bodies (without the leading 'windowrule = ') for this app."""
    m = matcher(cls)
    if not v.get("floating"):
        out = ["tile on, " + m]
    else:
        out = ["float on, " + m]
        if all(v.get(k) is not None for k in ("mon", "x", "y", "w", "h")):
            out += [f"monitor {v['mon']}, {m}",
                    f"size {v['w']} {v['h']}, {m}",
                    f"move {v['x']} {v['y']}, {m}"]
    # Maximized (SUPER+V = fullscreen mode 1) layers ON TOP of the float/size/move
    # above: the window opens maximized, and un-maximizing returns it to the saved
    # geometry. (Real fullscreen, mode 2, is never recorded — see poll_loop.)
    if v.get("maximized"):
        out.append("maximize on, " + m)
    return out


def write_conf():
    try:
        os.makedirs(os.path.dirname(CONF), exist_ok=True)
        out = ["# Auto-generated by ~/.config/hypr/window-geometry.py — remembered",
               "# per-app window state (tiled/floating + floating geometry),",
               "# regenerated whenever a window changes. Do not edit by hand.", ""]
        for cls in sorted(geo):
            for r in rules_for(cls, geo[cls]):
                out.append("windowrule = " + r)
        tmp = CONF + ".tmp"
        with open(tmp, "w") as f:
            f.write("\n".join(out) + "\n")
        os.replace(tmp, CONF)
    except Exception:
        pass


def write_state():
    try:
        os.makedirs(os.path.dirname(STATE), exist_ok=True)
        tmp = STATE + ".tmp"
        with open(tmp, "w") as f:
            json.dump(geo, f)
        os.replace(tmp, STATE)
    except Exception:
        pass


def _lua_str(s):
    # escape a value for embedding in a lua double-quoted string literal: double
    # backslashes (re.escape gives `^(brave\-browser)$`; a bare `\-` is an invalid
    # lua escape), then escape quotes.
    return s.replace("\\", "\\\\").replace('"', '\\"')


def _body_to_lua(body):
    """Convert a windowrule body ('size 700 400, match:class ^(X)$') into a
    STRUCTURED hl.window_rule(...) eval string. CRITICAL: under the Lua config the
    raw-string form hl.window_rule({"size .., match:.."}) is silently accepted but
    size/move/tile/monitor NEVER apply — only the table form works (verified). This
    mirrors apply_windowrule() in hyprland.lua so live + startup behave identically."""
    parts = [p.strip() for p in body.split(",")]
    match_fields = []
    for p in parts[1:]:
        if p.startswith("match:"):
            kv = p[len("match:"):].split(" ", 1)
            if len(kv) == 2:
                match_fields.append(f'{kv[0]} = "{_lua_str(kv[1])}"')
    verb, _, rest = parts[0].partition(" ")
    if verb in ("float", "tile", "fullscreen", "maximize"):
        action = f'{verb} = {"true" if rest == "on" else "false"}'
    elif verb in ("size", "move", "monitor"):
        action = f'{verb} = "{_lua_str(rest)}"'
    else:
        return 'hl.window_rule({"' + _lua_str(body) + '"})'  # unknown verb: raw fallback
    return f'hl.window_rule({{ match = {{ {", ".join(match_fields)} }}, {action} }})'


def apply_live(cls, v):
    """Apply the current rules live so a reopen THIS session uses the latest state.
    Under the Lua config `hyprctl keyword` is REJECTED, AND the raw-string
    hl.window_rule form silently no-ops for size/move/tile — so emit the STRUCTURED
    hl.window_rule table via `hyprctl eval`. No unset needed: rules accumulate and
    the LATEST matching one wins (verified)."""
    for r in rules_for(cls, v):
        subprocess.run(["hyprctl", "eval", _body_to_lua(r) + " return 1"],
                       stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)


def poll_loop():
    global _max_mons
    # Addresses seen on the PREVIOUS poll. A window is only recorded once it has
    # persisted ≥1 interval — so a splash/loader that flashes up and vanishes
    # within a poll is never recorded (this is the "shotcut splash" problem).
    prev_addrs = set()
    while True:
        time.sleep(POLL)
        mons = hyprctl_json("monitors")
        cls_list = hyprctl_json("clients")
        if mons is None or cls_list is None:
            continue
        # Pause recording while a monitor is missing (e.g. powered off overnight):
        # windows pile onto the remaining monitor, and we must NOT overwrite the
        # real saved geometry with that squished layout. Resume once all are back.
        _max_mons = max(_max_mons, len(mons))
        if len(mons) < _max_mons:
            continue
        moff = {m["id"]: (m["name"], m["x"], m["y"]) for m in mons}

        # Group this poll's eligible windows by class. An app's dialogs, popups
        # and splash share its class, so keying on class alone let whichever one
        # came last in the list overwrite the main window's saved geometry. Pick
        # ONE canonical window per class instead: the largest-area surface that
        # has persisted ≥1 poll. The main window is reliably the biggest, and is
        # always older than any dialog it spawns — so dialogs/popups/splashes are
        # skipped while the real window is recorded.
        cur_addrs = set()
        per_class = {}
        for c in cls_list:
            cls = c.get("class") or ""
            addr = c.get("address") or ""
            if not cls or cls in EXCLUDE or not addr:
                continue
            ws = (c.get("workspace") or {}).get("name", "")
            if ws.startswith("special"):
                continue
            cur_addrs.add(addr)
            if addr not in prev_addrs:        # not stable yet — skip this poll
                continue
            sz = c.get("size") or [0, 0]
            per_class.setdefault(cls, []).append(((sz[0] or 0) * (sz[1] or 0), c))

        changed = False
        for cls, lst in per_class.items():
            _, c = max(lst, key=lambda t: t[0])   # largest-area window of this class
            fs = c.get("fullscreen") or 0   # 0=none 1=maximize(SUPER+V) 2=fullscreen
            if fs == 2:
                # Real fullscreen (games / video) is a transient mode, not a per-app
                # preference — never record it (its bounds would also clobber the
                # saved floating geometry). Leave the prior state untouched.
                continue
            if fs == 1:
                # Maximized: its at/size are the maximized bounds, NOT the real
                # floating geometry — keep the prior floating/tiled geometry and
                # just flag maximized, so un-maximizing later restores correctly.
                val = dict(geo.get(cls, {}))
                val.setdefault("floating", True)
                val["maximized"] = True
            elif c.get("floating"):
                at, sz, mid = c.get("at"), c.get("size"), c.get("monitor")
                if not at or not sz or sz[0] < MIN_SIZE or sz[1] < MIN_SIZE:
                    continue
                if mid not in moff:
                    continue
                mon, mx, my = moff[mid]
                val = {"floating": True, "maximized": False, "mon": mon,
                       "x": at[0] - mx, "y": at[1] - my, "w": sz[0], "h": sz[1]}
            else:
                # Tiled: flip the flag but keep any prior floating geometry, so
                # un-tiling later returns the window to where it last floated.
                val = dict(geo.get(cls, {}))
                val["floating"] = False
                val["maximized"] = False
            if geo.get(cls) != val:
                geo[cls] = val
                apply_live(cls, val)
                changed = True
        if changed:
            write_state()
            write_conf()
        prev_addrs = cur_addrs


if __name__ == "__main__":
    # Single instance: a reload/relaunch (or a stale daemon from a prior session)
    # otherwise leaves two pollers racing on the same state + conf. Hold an
    # exclusive lock for our whole lifetime; a second copy exits immediately.
    _lock_path = os.path.expanduser("~/.local/state/hypr/window-geometry.lock")
    os.makedirs(os.path.dirname(_lock_path), exist_ok=True)
    _lock = open(_lock_path, "w")
    try:
        fcntl.flock(_lock, fcntl.LOCK_EX | fcntl.LOCK_NB)
    except OSError:
        raise SystemExit(0)
    poll_loop()
